# Generated by Django 3.2.5 on 2021-08-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorsnbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='some notes'),
        ),
        migrations.AlterField(
            model_name='books',
            name='desc',
            field=models.TextField(default='some desc'),
        ),
    ]
