# Generated by Django 3.2.5 on 2021-08-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0002_dojo_ninja'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='desc'),
        ),
    ]
