# Generated by Django 3.2.5 on 2021-08-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0003_dojo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='power',
            field=models.IntegerField(default=12),
        ),
    ]
