# Generated by Django 3.2.5 on 2021-08-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0004_dojo_power'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dojo',
            old_name='power',
            new_name='power_force',
        ),
    ]
